AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HTTP API

Parameters:
  IssuerUrl:
    Type: String
    Description: Issuer URL for your Auth0 Api
  APIAudience:
    Type: String
    Description: The identifier value of the API you created in the Auth0 API

Globals:
  Function:
    Timeout: 5
    MemorySize: 1536
    Runtime: java8.al2
    Handler: com.auth.App::handleRequest
    CodeUri: auth-functions

Resources:

  CustomLambdaAuth:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CustomLambdaAuth
      Handler: com.auth.CustomLambdaAuth::handleRequest

  Auth0CustomLambdaAuth:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Auth0CustomLambdaAuth
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: auth0-custom-auth-lambda
      Timeout: 15
      Environment:
        Variables:
          JWKS_URI: !Sub "${IssuerUrl}.well-known/jwks.json"
          TOKEN_ISSUER: !Ref IssuerUrl
          AUDIENCE: !Ref APIAudience

  LambdaAuthInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/service-role/"
      Policies:
        - PolicyName: InvokeAuthLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt CustomLambdaAuth.Arn
        - PolicyName: Auth0CustomLambdaInvoke
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt Auth0CustomLambdaAuth.Arn


  SampleRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        Authorizers:
          Auth0CustomAuthorizer:
            FunctionInvokeRole: !GetAtt LambdaAuthInvokeRole.Arn
            FunctionArn: !GetAtt Auth0CustomLambdaAuth.Arn
            IdentitySource: "$request.header.Authorization"
            FunctionPayloadType: TOKEN

  SampleHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          GeneralAuth:
            AuthorizationScopes:
              - email
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Ref IssuerUrl
              audience:
                - !Ref APIAudience
          CustomLambdaAuthorizer:
            AuthorizerPayloadFormatVersion: 2.0
            EnableSimpleResponses: True
            FunctionInvokeRole: !GetAtt LambdaAuthInvokeRole.Arn
            FunctionArn: !GetAtt CustomLambdaAuth.Arn
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 5
      CorsConfiguration:
        AllowMethods:
          - GET
        AllowOrigins:
          - http://localhost:3000

  # Open route
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /
            Method: get
            ApiId: !Ref SampleHttpApi
        RestRootGet:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref SampleRestApi

  # Auth0 auth
  SimpleAuthLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        Auth0Get:
          Type: HttpApi
          Properties:
            Auth:
              Authorizer: GeneralAuth
            Path: "/auth0"
            Method: get
            ApiId: !Ref SampleHttpApi
        RestAuth0Get:
          Type: Api
          Properties:
            Auth:
              Authorizer: Auth0CustomAuthorizer
            Path: "/auth0"
            Method: get
            RestApiId: !Ref SampleRestApi

  CustomLambdaAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        CustomAuth:
          Type: HttpApi
          Properties:
            Auth:
              Authorizer: CustomLambdaAuthorizer
            Path: /custom
            Method: get
            ApiId: !Ref SampleHttpApi

  # $default route used as catchall
  CatchAllLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref SampleHttpApi
        RestCatchAll:
          Type: Api
          Properties:
            Path: /{all+}
            Method: get
            RestApiId: !Ref SampleRestApi


Outputs:
  ApiEndpoint:
    Description: "HTTP API endpoint URL"
    Value: !Sub "https://${SampleHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  RestApiEndpoint:
    Description: "Rest API endpoint URL"
    Value: !Sub "https://${SampleRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
